- name: Hello World Sample
  hosts: all

  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
     
    - name: install the latest version of Apache
      yum:
        name: httpd
        state: latest

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

     - name: List ansible packages and register result to print with debug later.
       yum:
         list: ansible
       register: result
